// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type UserRole string

const (
	UserRoleCANDIDATE UserRole = "CANDIDATE"
	UserRoleRECRUITER UserRole = "RECRUITER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Application struct {
	ID            pgtype.UUID        `json:"id"`
	JobID         pgtype.UUID        `json:"job_id"`
	CandidateID   pgtype.UUID        `json:"candidate_id"`
	Status        string             `json:"status"`
	MatchScore    pgtype.Int4        `json:"match_score"`
	GatewayAnswer pgtype.Text        `json:"gateway_answer"`
	GatewayGrade  pgtype.Text        `json:"gateway_grade"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID                    pgtype.UUID        `json:"id"`
	RecruiterID           pgtype.UUID        `json:"recruiter_id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	Embedding             pgvector.Vector    `json:"embedding"`
	GatewayQuestion       pgtype.Text        `json:"gateway_question"`
	IsPaid                pgtype.Bool        `json:"is_paid"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	JobType               pgtype.Text        `json:"job_type"`
	LocationType          pgtype.Text        `json:"location_type"`
	LocationCity          pgtype.Text        `json:"location_city"`
	SalaryMin             pgtype.Int4        `json:"salary_min"`
	SalaryMax             pgtype.Int4        `json:"salary_max"`
	Currency              pgtype.Text        `json:"currency"`
	ExperienceMin         pgtype.Int4        `json:"experience_min"`
	ExperienceMax         pgtype.Int4        `json:"experience_max"`
	Benefits              pgtype.Text        `json:"benefits"`
	Requirements          pgtype.Text        `json:"requirements"`
	JobSummary            pgtype.Text        `json:"job_summary"`
	EducationRequirements pgtype.Text        `json:"education_requirements"`
	SkillsRequirements    pgtype.Text        `json:"skills_requirements"`
	Languages             pgtype.Text        `json:"languages"`
	WorkConditions        pgtype.Text        `json:"work_conditions"`
	IsUnpaid              pgtype.Bool        `json:"is_unpaid"`
	RecruiterEmail        pgtype.Text        `json:"recruiter_email"`
	Status                pgtype.Text        `json:"status"`
}

type User struct {
	ID                   pgtype.UUID        `json:"id"`
	WalletAddress        pgtype.Text        `json:"wallet_address"`
	Email                pgtype.Text        `json:"email"`
	Role                 UserRole           `json:"role"`
	Karma                pgtype.Int4        `json:"karma"`
	IsPro                pgtype.Bool        `json:"is_pro"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	FullName             pgtype.Text        `json:"full_name"`
	PasswordHash         pgtype.Text        `json:"password_hash"`
	Bio                  pgtype.Text        `json:"bio"`
	Skills               pgtype.Text        `json:"skills"`
	Experience           pgtype.Text        `json:"experience"`
	Projects             []byte             `json:"projects"`
	JobRole              pgtype.Text        `json:"job_role"`
	Education            pgtype.Text        `json:"education"`
	Phone                pgtype.Text        `json:"phone"`
	OrganizationName     pgtype.Text        `json:"organization_name"`
	OrganizationLocation pgtype.Text        `json:"organization_location"`
	OrganizationBio      pgtype.Text        `json:"organization_bio"`
	ProfessionalEmail    pgtype.Text        `json:"professional_email"`
}
